// Minimal, dependency-free i18n for the card. Falls back to German if the
// Home Assistant UI language has no translation, then to the raw key.
// Add further languages by adding another top-level entry to STRINGS.

type Dict = Record<string, string>;

const de: Dict = {
  "view.today": "Heute",
  "view.day": "Tag",
  "view.week": "Woche",
  "view.month": "Monat",
  "view.agenda": "Agenda",
  "nav.today": "Heute",
  "nav.prev": "Zurück",
  "nav.next": "Weiter",
  "action.add_event": "Termin hinzufügen",
  "action.search": "Suchen",
  "action.filter": "Filter",
  "action.save": "Speichern",
  "action.cancel": "Abbrechen",
  "action.delete": "Löschen",
  "action.edit": "Bearbeiten",
  "action.duplicate": "Duplizieren",
  "action.close": "Schließen",
  "action.done": "Fertig",
  "action.mark_done": "Als erledigt markieren",
  "action.manage_people": "Personen verwalten",
  "action.manage_categories": "Kategorien verwalten",
  "action.export": "Als JSON exportieren",
  "action.import": "JSON importieren",
  "event.title": "Titel",
  "event.subtitle": "Untertitel",
  "event.start_date": "Startdatum",
  "event.start_time": "Startzeit",
  "event.end_date": "Enddatum",
  "event.end_time": "Endzeit",
  "event.all_day": "Ganztägig",
  "event.people": "Personen",
  "event.description": "Beschreibung",
  "event.location": "Ort",
  "event.category": "Kategorie",
  "event.color": "Farbe",
  "event.icon": "Symbol",
  "event.status": "Status",
  "event.reminders": "Erinnerungen",
  "event.repeat": "Wiederholung",
  "event.repeat_none": "Keine Wiederholung",
  "event.new_title": "Neuer Termin",
  "event.edit_title": "Termin bearbeiten",
  "event.no_people": "Keine Person zugewiesen",
  "status.planned": "Geplant",
  "status.confirmed": "Bestätigt",
  "status.tentative": "Optional",
  "status.done": "Erledigt",
  "status.cancelled": "Abgesagt",
  "validation.title_required": "Bitte einen Titel eingeben.",
  "validation.end_before_start": "Das Ende darf nicht vor dem Start liegen.",
  "validation.person_required": "Bitte mindestens eine Person auswählen.",
  "empty.no_events": "Keine Termine",
  "empty.no_events_hint": "Für diesen Zeitraum sind keine Termine vorhanden. Tippe auf +, um einen Termin zu erstellen.",
  "month.more": "+{count} weitere",
  "dialog.confirm_delete_title": "Termin löschen?",
  "dialog.confirm_delete_series": "Ganze Serie löschen",
  "dialog.confirm_delete_instance": "Nur diesen Termin löschen",
  "dialog.unsaved_changes_title": "Ungespeicherte Änderungen",
  "dialog.unsaved_changes_message": "Es gibt ungespeicherte Änderungen. Trotzdem schließen?",
  "dialog.discard": "Verwerfen",
  "dialog.keep_editing": "Weiter bearbeiten",
  "people.title": "Personen",
  "people.add": "Person hinzufügen",
  "people.name": "Name",
  "people.color": "Farbe",
  "people.role": "Rolle",
  "people.role.parent": "Elternteil",
  "people.role.child": "Kind",
  "people.role.other": "Sonstige",
  "people.active": "Aktiv",
  "people.delete_title": "Person löschen?",
  "people.delete_strategy.deactivate": "Nur deaktivieren",
  "people.delete_strategy.remove_from_events": "Aus Terminen entfernen",
  "people.delete_strategy.reassign": "Terminen einer anderen Person zuweisen",
  "people.delete_strategy.keep_unassigned": "Termine ohne Personenzuweisung behalten",
  "people.reassign_to": "Neu zuweisen an",
  "category.title": "Kategorien",
  "category.add": "Kategorie hinzufügen",
  "category.name": "Name",
  "category.color": "Farbe",
  "category.none": "Keine Kategorie",
  "filter.all_people": "Alle Personen",
  "filter.search_placeholder": "Termine durchsuchen…",
  "error.connection_lost": "Verbindung zu Home Assistant verloren. Es wird versucht, erneut zu verbinden…",
  "error.forbidden": "Keine Berechtigung für diese Aktion.",
  "error.conflict": "Dieser Termin wurde inzwischen auf einem anderen Gerät geändert.",
  "error.not_found": "Dieser Termin existiert nicht mehr.",
  "error.invalid_data": "Ungültige Eingabe.",
  "error.not_loaded": "Family Planner wird noch geladen…",
  "error.unknown_error": "Unbekannter Fehler.",
  "error.reload": "Neu laden",
  "reminder.at_start": "Zum Startzeitpunkt",
  "reminder.5": "5 Minuten vorher",
  "reminder.15": "15 Minuten vorher",
  "reminder.30": "30 Minuten vorher",
  "reminder.60": "1 Stunde vorher",
  "reminder.1440": "1 Tag vorher",
  "reminder.custom": "Eigener Wert (Minuten)",
  "weekday.short.0": "So",
  "weekday.short.1": "Mo",
  "weekday.short.2": "Di",
  "weekday.short.3": "Mi",
  "weekday.short.4": "Do",
  "weekday.short.5": "Fr",
  "weekday.short.6": "Sa",
  "calendar_week_short": "KW",
};

const en: Dict = {
  "view.today": "Today",
  "view.day": "Day",
  "view.week": "Week",
  "view.month": "Month",
  "view.agenda": "Agenda",
  "nav.today": "Today",
  "nav.prev": "Previous",
  "nav.next": "Next",
  "action.add_event": "Add event",
  "action.search": "Search",
  "action.filter": "Filter",
  "action.save": "Save",
  "action.cancel": "Cancel",
  "action.delete": "Delete",
  "action.edit": "Edit",
  "action.duplicate": "Duplicate",
  "action.close": "Close",
  "action.done": "Done",
  "action.mark_done": "Mark as done",
  "action.manage_people": "Manage people",
  "action.manage_categories": "Manage categories",
  "action.export": "Export as JSON",
  "action.import": "Import JSON",
  "event.title": "Title",
  "event.subtitle": "Subtitle",
  "event.start_date": "Start date",
  "event.start_time": "Start time",
  "event.end_date": "End date",
  "event.end_time": "End time",
  "event.all_day": "All day",
  "event.people": "People",
  "event.description": "Description",
  "event.location": "Location",
  "event.category": "Category",
  "event.color": "Color",
  "event.icon": "Icon",
  "event.status": "Status",
  "event.reminders": "Reminders",
  "event.repeat": "Repeat",
  "event.repeat_none": "Does not repeat",
  "event.new_title": "New event",
  "event.edit_title": "Edit event",
  "event.no_people": "No one assigned",
  "status.planned": "Planned",
  "status.confirmed": "Confirmed",
  "status.tentative": "Tentative",
  "status.done": "Done",
  "status.cancelled": "Cancelled",
  "validation.title_required": "Please enter a title.",
  "validation.end_before_start": "The end must not be before the start.",
  "validation.person_required": "Please select at least one person.",
  "empty.no_events": "No events",
  "empty.no_events_hint": "There are no events in this range. Tap + to create one.",
  "month.more": "+{count} more",
  "dialog.confirm_delete_title": "Delete event?",
  "dialog.confirm_delete_series": "Delete whole series",
  "dialog.confirm_delete_instance": "Delete only this occurrence",
  "dialog.unsaved_changes_title": "Unsaved changes",
  "dialog.unsaved_changes_message": "You have unsaved changes. Close anyway?",
  "dialog.discard": "Discard",
  "dialog.keep_editing": "Keep editing",
  "people.title": "People",
  "people.add": "Add person",
  "people.name": "Name",
  "people.color": "Color",
  "people.role": "Role",
  "people.role.parent": "Parent",
  "people.role.child": "Child",
  "people.role.other": "Other",
  "people.active": "Active",
  "people.delete_title": "Delete person?",
  "people.delete_strategy.deactivate": "Deactivate only",
  "people.delete_strategy.remove_from_events": "Remove from events",
  "people.delete_strategy.reassign": "Reassign events to another person",
  "people.delete_strategy.keep_unassigned": "Keep events without a person assigned",
  "people.reassign_to": "Reassign to",
  "category.title": "Categories",
  "category.add": "Add category",
  "category.name": "Name",
  "category.color": "Color",
  "category.none": "No category",
  "filter.all_people": "All people",
  "filter.search_placeholder": "Search events…",
  "error.connection_lost": "Connection to Home Assistant lost. Reconnecting…",
  "error.forbidden": "You are not allowed to do this.",
  "error.conflict": "This event was changed on another device in the meantime.",
  "error.not_found": "This event no longer exists.",
  "error.invalid_data": "Invalid input.",
  "error.not_loaded": "Family Planner is still loading…",
  "error.unknown_error": "Unknown error.",
  "error.reload": "Reload",
  "reminder.at_start": "At start time",
  "reminder.5": "5 minutes before",
  "reminder.15": "15 minutes before",
  "reminder.30": "30 minutes before",
  "reminder.60": "1 hour before",
  "reminder.1440": "1 day before",
  "reminder.custom": "Custom (minutes)",
  "weekday.short.0": "Sun",
  "weekday.short.1": "Mon",
  "weekday.short.2": "Tue",
  "weekday.short.3": "Wed",
  "weekday.short.4": "Thu",
  "weekday.short.5": "Fri",
  "weekday.short.6": "Sat",
  "calendar_week_short": "W",
};

const STRINGS: Record<string, Dict> = { de, en };

export function t(language: string | undefined, key: string, vars?: Record<string, string | number>): string {
  const lang = (language || "de").split("-")[0];
  const dict = STRINGS[lang] || STRINGS.de;
  let value = dict[key] ?? STRINGS.de[key] ?? key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      value = value.replace(`{${k}}`, String(v));
    }
  }
  return value;
}
